### PR TITLE
Build docker images

### PR DESCRIPTION
**Pull request by FarisZR**
Hi, thanks for the great fork/project.

I created this simple PR to create docker images on push for the develop branch.
I still selected the pr to be to the main branch as AFAIK actions won't run if the file is not in the main branch.

The files will build the image for amd64, arm64 and armv7.
There will be two tags, dev for the development branch, and latest for any pushes on the main branch.

I added publishing to docker hub, since you seem to have an [account](https://hub.docker.com/u/maranda) on it, but I can remove, so it only pushes to ghcr.io.

### CODE REVIEW

**Comment by Neustradamus** [comment]
@maranda: Have you seen this PR?

**Comment by maranda** [comment]
@FarisZR Thanks for the PR, sorry I seen it just now but with the various recent turmoils I missed it

**Comment by Neustradamus** [comment]
@maranda: No problem, it is a pleasure to inform you :)

**Comment by FarisZR** [comment]
Make sure to create a repo on docker hub, and set DOCKERHUB_USERNAME and DOCKERHUB_TOKEN.
The build failed because there is no password set.

**Comment by maranda** [comment]
> Make sure to create a repo on docker hub, and set DOCKERHUB_USERNAME and DOCKERHUB_TOKEN. The build failed because there is no password set.

Done, I will run 'em manually

**Pull request merged**
